ADJECTIVES = [
    "Advanced",
    "Basic",
    "Compact",
    "Durable",
    "Efficient",
    "Ergonomic",
    "Innovative",
    "Lightweight",
    "Portable",
    "Robust",
    "Smart",
    "Sleek",
    "Sophisticated",
    "Streamlined",
    "Versatile",
]

CATEGORIES_DESCRIPTIONS = [
    "Featuring the latest technology and design for superior performance. Ideal for tech enthusiasts.",
    "Simple and easy to use, perfect for everyday tasks. Great for beginners.",
    "Small in size but big on functionality, ideal for limited spaces. Perfect for compact living.",
    "Built to last with high-quality materials and construction. Suitable for rugged use.",
    "Optimized for maximum productivity and minimal waste. Excellent for efficiency seekers.",
    "Designed for comfort and ease of use, reducing strain. Perfect for long-term use.",
    "Cutting-edge features and design for modern needs. Ideal for innovators.",
    "Easy to carry and handle, without sacrificing performance. Great for travelers.",
    "Convenient to transport, perfect for on-the-go use. Suitable for mobile professionals.",
    "Strong and reliable, capable of handling tough conditions. Perfect for heavy-duty tasks.",
    "Intelligent features that make tasks easier and more efficient. Ideal for smart homes.",
    "Stylish and modern design that looks great anywhere. Perfect for fashion-conscious users.",
    "Elegant and refined, with advanced capabilities. Suitable for sophisticated tastes.",
    "Smooth and efficient design for optimal performance. Great for streamlined operations.",
    "Adaptable to a wide range of tasks and situations. Perfect for versatile applications.",
]

NOUNS = [
    "Adapter",
    "Analyzer",
    "Calculator",
    "Device",
    "Gadget",
    "Instrument",
    "Module",
    "Platform",
    "Processor",
    "Sensor",
    "System",
    "Tool",
    "Tesler",
    "Unit",
    "Widget",
    "Workstation",
    "Framework",
    "Interface",
    "Engine",
    "Hub",
]

DESCRIPTIONS = [
    "This is an absolutely fantastic product. People are talking about it, believe me! It combines exceptional quality with unmatched performance, making it a must-have for anyone looking to elevate their experience.",
    "You are going to love this product—many, many people already do. It’s that good! With its innovative design and user-friendly features, it’s perfect for anyone who values convenience and efficiency.",
    "This product is top-notch, folks. Nobody does it better. Incredible quality! Crafted with precision and care, it’s built to exceed expectations and deliver outstanding results every time.",
    "So many people are saying this—highly recommended! A total winner! Whether you’re a professional or a hobbyist, this product is designed to meet your needs and help you achieve your goals effortlessly.",
    "Best in its class, no question about it. Everyone agrees. Tremendous value! It offers a perfect balance of affordability and premium features, making it an excellent choice for budget-conscious buyers.",
    "Listen, this is a must-have for everyone. If you don’t have it, you’re missing out! It’s packed with features that make your life easier, ensuring you get the most out of every use.",
    "The quality and performance? Unbelievable! You’ve never seen anything like it! Engineered to perfection, it delivers consistent and reliable results, no matter the task at hand.",
    "Durability, reliability—nothing else comes close. It just doesn’t break! Made with high-quality materials, it’s designed to withstand the test of time and handle even the toughest conditions.",
    "Designed with YOU in mind. Because you deserve the very best, and that’s what this is! Every detail has been carefully considered to provide an exceptional user experience that you’ll appreciate every day.",
    "So many innovations, so many incredible features—nothing else even compares! It’s a game-changer that sets a new standard for excellence, redefining what’s possible in its category.",
]
