ADJECTIVES = [
    "Advanced",
    "Basic",
    "Compact",
    "Durable",
    "Efficient",
    "Ergonomic",
    "Innovative",
    "Lightweight",
    "Portable",
    "Robust",
    "Smart",
    "Sleek",
    "Sophisticated",
    "Streamlined",
    "Versatile",
]

CATEGORIES_DESCRIPTIONS = [
    "Featuring the latest technology and design for superior performance. Ideal for tech enthusiasts.",
    "Simple and easy to use, perfect for everyday tasks. Great for beginners.",
    "Small in size but big on functionality, ideal for limited spaces. Perfect for compact living.",
    "Built to last with high-quality materials and construction. Suitable for rugged use.",
    "Optimized for maximum productivity and minimal waste. Excellent for efficiency seekers.",
    "Designed for comfort and ease of use, reducing strain. Perfect for long-term use.",
    "Cutting-edge features and design for modern needs. Ideal for innovators.",
    "Easy to carry and handle, without sacrificing performance. Great for travelers.",
    "Convenient to transport, perfect for on-the-go use. Suitable for mobile professionals.",
    "Strong and reliable, capable of handling tough conditions. Perfect for heavy-duty tasks.",
    "Intelligent features that make tasks easier and more efficient. Ideal for smart homes.",
    "Stylish and modern design that looks great anywhere. Perfect for fashion-conscious users.",
    "Elegant and refined, with advanced capabilities. Suitable for sophisticated tastes.",
    "Smooth and efficient design for optimal performance. Great for streamlined operations.",
    "Adaptable to a wide range of tasks and situations. Perfect for versatile applications.",
]

NOUNS = [
    "Adapter",
    "Analyzer",
    "Calculator",
    "Device",
    "Gadget",
    "Instrument",
    "Module",
    "Platform",
    "Processor",
    "Sensor",
    "System",
    "Tool",
    "Tesler",
    "Unit",
    "Widget",
    "Workstation",
    "Framework",
    "Interface",
    "Engine",
    "Hub",
]

DESCRIPTIONS = [
    "This is an absolutely fantastic product. People are talking about it, believe me!",
    "You are going to love this product—many, many people already do. It’s that good!",
    "This product is top-notch, folks. Nobody does it better. Incredible quality!",
    "So many people are saying this—highly recommended! A total winner!",
    "Best in its class, no question about it. Everyone agrees. Tremendous value!",
    "Listen, this is a must-have for everyone. If you don’t have it, you’re missing out!",
    "The quality and performance? Unbelievable! You’ve never seen anything like it!",
    "Durability, reliability—nothing else comes close. It just doesn’t break!",
    "Designed with YOU in mind. Because you deserve the very best, and that’s what this is!",
    "So many innovations, so many incredible features—nothing else even compares!",
]
