ADJECTIVES = [
    "Advanced",
    "Basic",
    "Compact",
    "Durable",
    "Efficient",
    "Ergonomic",
    "Innovative",
    "Lightweight",
    "Portable",
    "Robust",
    "Smart",
    "Sleek",
    "Sophisticated",
    "Streamlined",
    "Versatile",
]

CATEGORIES_DESCRIPTIONS = [
    "Featuring the latest technology and design for superior performance. Ideal for tech enthusiasts.",
    "Simple and easy to use, perfect for everyday tasks. Great for beginners.",
    "Small in size but big on functionality, ideal for limited spaces. Perfect for compact living.",
    "Built to last with high-quality materials and construction. Suitable for rugged use.",
    "Optimized for maximum productivity and minimal waste. Excellent for efficiency seekers.",
    "Designed for comfort and ease of use, reducing strain. Perfect for long-term use.",
    "Cutting-edge features and design for modern needs. Ideal for innovators.",
    "Easy to carry and handle, without sacrificing performance. Great for travelers.",
    "Convenient to transport, perfect for on-the-go use. Suitable for mobile professionals.",
    "Strong and reliable, capable of handling tough conditions. Perfect for heavy-duty tasks.",
    "Intelligent features that make tasks easier and more efficient. Ideal for smart homes.",
    "Stylish and modern design that looks great anywhere. Perfect for fashion-conscious users.",
    "Elegant and refined, with advanced capabilities. Suitable for sophisticated tastes.",
    "Smooth and efficient design for optimal performance. Great for streamlined operations.",
    "Adaptable to a wide range of tasks and situations. Perfect for versatile applications.",
]

NOUNS = [
    "Adapter",
    "Analyzer",
    "Calculator",
    "Device",
    "Gadget",
    "Instrument",
    "Module",
    "Platform",
    "Processor",
    "Sensor",
    "System",
    "Tool",
    "Tesler",
    "Unit",
    "Widget",
    "Workstation",
    "Framework",
    "Interface",
    "Engine",
    "Hub",
]

DESCRIPTIONS = [
    "This product is designed to deliver exceptional quality and reliable performance. It combines advanced features with a user-friendly design, making it suitable for a wide range of applications.",
    "A highly functional product that emphasizes practicality and efficiency. Its innovative design ensures ease of use and consistent results, making it an excellent choice for everyday tasks.",
    "Crafted with precision and attention to detail, this product offers superior durability and performance. It is built to meet the demands of both professionals and casual users.",
    "Engineered to provide optimal functionality and long-lasting reliability. This product is ideal for those seeking a dependable solution for their specific needs.",
    "A versatile product that balances affordability with premium features. It is designed to cater to a variety of requirements, ensuring excellent value for money.",
    "This product is equipped with advanced features that simplify tasks and enhance productivity. Its robust construction ensures it can handle demanding conditions with ease.",
    "Designed for maximum efficiency and ease of use, this product delivers consistent performance. It is a dependable choice for users who prioritize quality and reliability.",
    "Built with high-quality materials, this product is designed to withstand rigorous use. Its durable construction ensures it remains functional over an extended period.",
    "A thoughtfully designed product that prioritizes user experience. Its intuitive features and ergonomic design make it a pleasure to use in any setting.",
    "This product sets a new standard in its category with its innovative features and superior performance. It is an excellent choice for those seeking cutting-edge solutions.",
    "An eco-friendly product designed with sustainability in mind. It combines functionality with environmental responsibility, making it a great choice for conscious consumers.",
    "A compact and portable product that offers convenience without compromising on performance. Ideal for users who require mobility and flexibility in their tools.",
    "This product is tailored for precision and accuracy, making it suitable for specialized tasks. Its advanced capabilities ensure reliable results every time.",
    "A stylish and modern product that blends aesthetics with functionality. It is designed to complement contemporary lifestyles while delivering exceptional performance.",
    "A high-capacity product that is perfect for demanding tasks. Its robust design ensures it can handle heavy workloads efficiently and effectively.",
]
